### ISSUE TITLE
Case studies page : Image and case study item should be equal height as per design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/MDW-Environmental-Services#13]
Devices : Ipad, Ipad(mini)-Landscape mode
![2016-05-12_1436](https://cloud.githubusercontent.com/assets/13309730/15210194/efa28784-1852-11e6-80fc-cf56458a4b55.png)

**Comment by Santosh-titan** [comment]
Image height will adjust depends on image width
