### ISSUE TITLE
Gallery page : Images should be full height and full width on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/MDW-Environmental-Services#15]
Devices : Ipad, Ipad(mini), Samsung E7, Itouch
![2016-05-12_1437](https://cloud.githubusercontent.com/assets/13309730/15210413/0e8a3042-1854-11e6-8658-d68b9ac97e99.png)
![2016-05-12_1513](https://cloud.githubusercontent.com/assets/13309730/15210451/30675618-1854-11e6-93c5-76c59d4bce26.png)

**Comment by Santosh-titan** [comment]
Image container should have fixed height and and image should display vertical middle.
