### ISSUE TITLE
Products single page : Thumbnails alignment is distorting on Samsung E7 and Itouch

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/MDW-Environmental-Services#20]
![2016-05-12_1441_001](https://cloud.githubusercontent.com/assets/13309730/15210878/e4dca0a2-1855-11e6-9292-278544245c92.png)
![2016-05-12_1441_002](https://cloud.githubusercontent.com/assets/13309730/15210881/e786bcac-1855-11e6-8cdd-35c73cc67f7d.png)

**Comment by Santosh-titan** [comment]
Won't fix Bug. Main image width won't be fixed so we can't abject small thumbs gallery.
