### ISSUE TITLE
Homepage - Content: Image shouldn't depend with the content in its right, it should be retained its length and not cut or covered with contents are not too long, as per design and scope.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#39]
**with long contents**

![image](https://cloud.githubusercontent.com/assets/13363508/15418224/290284fa-1e90-11e6-88e7-cebc2f4846dc.png)

**with short contents**
 
![image](https://cloud.githubusercontent.com/assets/13363508/15418342/100dd7a0-1e91-11e6-8d12-45d996eec472.png)

**design**

![image](https://cloud.githubusercontent.com/assets/13363508/15418392/7f59c948-1e91-11e6-9b63-94c1795cd084.png)

![image](https://cloud.githubusercontent.com/assets/13363508/15418363/36dbd5bc-1e91-11e6-941d-60050754b128.png)

**Comment by Santosh-titan** [comment]
featured  won't resize depends on content. see the screenshot bellow 
![screenshot-localhost 3000 2016-05-25 15-55-36](https://cloud.githubusercontent.com/assets/13828562/15536976/77e43f46-2291-11e6-9232-d209e9b3fa42.png)

**Comment by maehtitan** [comment]
@Santosh-titan Yes the image didn't resize but have you notice that it is being covered when the content is too small, Please see the design again below, image height changes in site you implemented compared to the design given.
![image](https://cloud.githubusercontent.com/assets/13363508/15561487/f407784e-2328-11e6-8484-38877250ae71.png)
