### ISSUE TITLE
Homepage - Content: "Read More" button compressed with the white layout below it should have space gap between them as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#40]
![image](https://cloud.githubusercontent.com/assets/13363508/15418433/e05ee03e-1e91-11e6-8f3e-9a03b3a8232c.png)

**Comment by Santosh-titan** [comment]
given design is about 2000px width and you have to test it in 2000px screen it will look same as in design. when it comes to small desktops images height will resize according to width.

**Comment by maehtitan** [comment]
@Santosh-titan I am reporting for the "Read More" button compressed with the white layout and not the image issue.

**Comment by roseliesromeo** [comment]
Read more button doesn't show at all.

**Comment by roseliesromeo** [comment]
It doesn't show after adding one more paragraph.
![image](https://cloud.githubusercontent.com/assets/11186313/15843284/8f36098e-2c93-11e6-8381-2b10ea7e9c71.png)
