### ISSUE TITLE
Homepage - Latest News: As per scope and design it should be displayed the first 3 recent post and not 2 only

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#41]
![image](https://cloud.githubusercontent.com/assets/13363508/15418603/19ab2914-1e93-11e6-86a5-70127cebab6e.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15418638/40dc10c0-1e93-11e6-9c25-4f60d60eaca0.png)

**Comment by Santosh-titan** [comment]
Its already displaying 3 posts.
