### ISSUE TITLE
Banner Section: Banner should be paused on hover when there are text contents added.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#47]
https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners

![image](https://cloud.githubusercontent.com/assets/13363508/15419944/3ae4a5f2-1e9c-11e6-8392-d4fc0a7b1e5e.png)

**Comment by Santosh-titan** [comment]
When you hover exactly on content it will stop otherwise it won't because it is two layer banner.
