### ISSUE TITLE
Banner Section - Responsive Checking: Images isn't retain its full image width.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#49]
**Viewport sizes:
320px - 1140px**  
![image](https://cloud.githubusercontent.com/assets/13363508/15420836/7625a008-1ea1-11e6-800b-4673a9d2140b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15420842/85e6a6c2-1ea1-11e6-8000-c1d474a0404d.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15420851/8f163550-1ea1-11e6-9868-5cd1375aae18.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15420854/97b4db4e-1ea1-11e6-9f2c-ab1fff7513b0.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15420872/a7a5009c-1ea1-11e6-9f8c-dc18b8550718.png)

**til 1140px**

**Comment by Santosh-titan** [comment]
Banner image will adjust based on header, because we are displaying header and capability icons(yellow icons) with in banner.

**Comment by maehtitan** [comment]
You can position the Capability icon below the banner if banner image width reduces

**Comment by Santosh-titan** [comment]
Capability icons has been moved below the banner after 767px view

**Comment by roseliesromeo** [comment]
Banner images should be fully responsive maintaining it's aspect ration.

**Comment by Santosh-titan** [comment]
Banner image is responsive and banner image will adjust based on header, because we are displaying header and capability icons(yellow icons) with in banner.

**Comment by roseliesromeo** [comment]
Display other items below the banner if height cannot accommodate them. Banner images should be fully responsive.

**Comment by roseliesromeo** [comment]
Not fixed from 768 resolution and above. Banner image is still cut.
![image](https://cloud.githubusercontent.com/assets/11186313/15880219/ef694198-2d5d-11e6-9c32-cb308de947d3.png)

You can refer to this site: wonderwalls.stage.titanweb.com.au

Also for 320-640 resolution
Banner text are not fully displayed. Display them below the banner to show the full description.
640 resolution
![image](https://cloud.githubusercontent.com/assets/11186313/15880262/3643e744-2d5e-11e6-988b-1f92ec80e02a.png)
320 resolution
![image](https://cloud.githubusercontent.com/assets/11186313/15880270/3c338a60-2d5e-11e6-9767-a415ec76515b.png)

**Comment by Santosh-titan** [comment]
AS per reference link banner has been redesigned and banner image dimensions should be 1920x762
