### ISSUE TITLE
Homepage - MDW Group: No title and description reflected at the front-end.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Environmental-Services#66]
![image](https://cloud.githubusercontent.com/assets/13363508/15562736/7f8695f2-2334-11e6-901a-ebf8d00a62bd.png)

**Comment by Santosh-titan** [comment]
Initially it was implemented but after that "Cyril Balatero" has worked on that and he commented the code. anyway comment has been removed now.

**Comment by maehtitan** [comment]
I am not aware that there are changes that Bill has been requested, please revert it back and refer this thread: https://github.com/titan-cebu/MDW-Environmental-Services/issues/66#issuecomment-222080310

**Comment by roseliesromeo** [comment]
Please revert to changes made by Cyril Balatero for this item.
