### ISSUE TITLE
Banner: Inconsistent height of the banner images between home page and inner pages. Inner pages banner doesn't re-sized and with gradient applied except for products page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/MDW-Environmental-Services#81]
![image](https://cloud.githubusercontent.com/assets/11186313/15995059/b4f7c0b0-3146-11e6-9f80-017041fed80e.png)

**Comment by Santosh-titan** [comment]
As per design height of the inner banner and home page banner won't be same. Inner banner should always smaller than home page. Please see the design for inner pages. and banner gradient has been removed for inner banner in devices.
